services:
#    user.example:
#        class: User\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    login_listener:
        # path of the previously created class
        class:  User\UserBundle\Listeners\LoginListener
        arguments:
            - "@fos_user.user_manager"
            - "@router"
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }

    register_listener:
        # path of the previously created class
        class:  User\UserBundle\Listeners\LoginListener
        arguments:
            - "@fos_user.user_manager"
            - "@router"
        tags:
            - { name: kernel.event_listener, event: fos_user.registration.success, method: register }